### ISSUE TITLE
Launch Intent

### ISSUE THREAD

**Issue by srathi7** [aasthaagrawal/Speech_Therapy_Practice#1]
Opening the alexa skill. When user says 'Alexa, open Speech Therapy Practice', alexa should repeat back 'Welcome to Speech Therapy Practice. What do you want to practice today?'. There should also be a re-prompt to ask what to practice.

**Comment by aasthaagrawal** [comment]
@srathi7 For this issue, i directly pushed to master. Had forgotten to keep a separate working branch. Will do that from next issue. 

Please have a look at commit: https://github.com/aasthaagrawal/Speech_Therapy_Practice/commit/42e59a19946129dc0e3a80f55346a96163476323.

I'll close this issue. This would tested eventually.
