### ISSUE TITLE
Practice Create

### ISSUE THREAD

**Issue by srathi7** [aasthaagrawal/Speech_Therapy_Practice#2]
Create a slot to store what the user told he/she wants to practice. Repeat to the user what he/she wants to practice. A response from user should be expected which would be used to invoke next intent.

This intent might be used at any point to change the practice topic/theme. Check this functionality.

Note:  This slot attribute need not be persisted across sessions. So only keeping it in slot should do. Would have to check how to access attribute across different intents.

**Comment by aasthaagrawal** [comment]
Ready for Review
